---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: elrepo-centos-7
    image: docker.io/centos:7
    pre_build_image: true
  - name: elrepo-centos-8
    image: docker.io/centos:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: ansible-lint .
